### ISSUE TITLE
how to handle PIDs that don't resolve

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#100]
Attempts to resolve a PID that is not in the database gets a 404 and goes to an error page suggesting to contribute the PID. e.g. https://geoconnex.us/foobar 

Should there be a different page/ content for a situation where the PID is in the database but the target URL is 404 or the host is not found? Potentially a templated error message saying something is wrong with the target, contact the email address from the "creator" field.

**Comment by dblodgett-usgs** [comment]
Seems like a problem to take on a little further down the road?

**Comment by ksonda** [comment]
closing this since it's not clear how we'd solve this with current stack and also not very important right now
