### ISSUE TITLE
How to handle very large sets of redirects?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#11]
I'd like to add a few things that are very large. e.g. 2.7 million COMIDs. 

I really like the declarative csv/json-ld but the file size is too big for git when the number of redirects gets too big. In these kinds of cases, we could support regex-based redirects. 

Maybe a simple format that we manually maintain initially? I manually created one then exported it by hand.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<backup xmlns="urn:csiro:xmlns:pidsvc:backup:1.0" type="partial" scope="record">
  <mapping>
    <path>^/nhdplusv2/comid/([0-9]+).*$</path>
    <type>Regex</type>
    <title>nhdplusV2 comid</title>
    <creator>iow</creator>
    <action>
      <type>303</type>
      <name>location</name>
      <value>https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/$1</value>
    </action>
  </mapping>
</backup>
```

Maybe we check that in after creating one by hand? If people want a regex redirect they just open an issue and we take care of it?

**Comment by ksonda** [comment]
We need to limit uploaded csvs to be <100MB is size to avoid upload errors. We do not want to burden contributors with setting up LFS.

There is also currently an unknown limit to what the PIDsvc API can handle. We do know that this limit is greater than 10,000.

It seems that there is a simple decision tree that we need to guide contributers through.

- A: If contributing _less than 10,000_ redirects, **upload a a csv/geoJSON with one redirect per record**
- B: If contributing _greater than 10,000_ but can _split the features by some logical, memorable, and repeatable criterion_, such as by a geography, sub-organization, or feature type **split the redirects into multiple csv/geoJSON files, each with less than 10,000 records**
- C: If contributing a redirect set numbering greater than 10,000 that _cannot be logically split_ , **submit an issue requesting partial (regular expression match-based) redirects, which admins will implement manually**
-D: If contributing a redirect set that generates a csv greater than 100MB, **submit an issue requesting partial (regular expression match-based) redirects, which admins will implement manually**

Eventually, the partial redirect set may be able to be implemented in a more automated way with a sufficiently fool-proof csv template and a good naming convention for these files

**Comment by dblodgett-usgs** [comment]
Good summary. 👍 

Once we have occasion to add some big ones -- which will be soon -- let's move this set of logic to the README or some other reference location. Will close for now.
