### ISSUE TITLE
What's the right way to handle thematic integrations?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#12]
@mikejohnson51 and @dwief-usgs and I are working on a couple things that need to be added to geoconnex.us -- things like waterfalls, dams, bridges, etc. 

These features are ostensibly "owned" by a local or national entity but we have national integrated datasets that can be sources of feature identity. My knee jerk is to just keep it simple and do `/dams` or `/bridges` and regex-redirect them to the integrated dataset.  

The id for this would be some id generated in the integrated source. The integrated source would be generated by a reproducible integrated workflow that could pull in multiple sources and mash them up.

Clearly this will be case by case, but do we think this will be a reasonable path?

**Comment by ksonda** [comment]
@dblodgett-usgs are you saying that there will be geoconnex.us/dams/*numbers* that are redirected to https://nid.sec.usace.army.mil/ords/f?p=105:113:8224188430807::NO::*numbers* ?

Or that we are going to enforce some kind of controlled vocabulary, so that there will be
geoconnex.us/NC-DWR/dams/*numbers* and geoconnex.us/CA-DWR/dams/*numbers* that some worker we create crawls, adding to an admin-managed geoconnex.us/dams/ over time?

**Comment by dblodgett-usgs** [comment]
huh... thought I responded to this. My github comments have been disappearing lately. 

I'm suggesting that there would be something kind of like 4. But that the organization would be an integrated dams dataset that could be crowd sourced.

**Comment by ksonda** [comment]
So lets say @mikejohnson51 and co combine USACE NID and some other stuff into their own web app ufokn.org/dams that generate/templates LC pages for all the dams they can find. 

Do we want that to be the defacto crowd-sourced dataset and have geoconnex.us/dams/*** OR geoconnex.us/ufokn/dams/** to 303 to ufokn.org/dams/** ? 

Or do we want geoconnex.us/dams/** to 303 to separate info.geoconnex.us/ LC pages hosted by the "community" aka us (a la #6) , and those in turn have json-ld markup linking to ufokn.org/dams/** LC pages as a seed dataset. And then "the crowd" might contribute meta-information on dams directly to either geoconnex.us/dams OR to UFOKN?

**Comment by dblodgett-usgs** [comment]
I'm thinking initially, we have `geoconnex.us/dams/**` 303 to `ufokn.org/dams/**` as long as they are willing to continue hosting things there. If there's a reason and/or support for consolidating things under `info.geoconnex.us`, that would be cool -- but I don't want to get out ahead of that.

**Comment by ksonda** [comment]
Easy enough. In that case the only thing is for now there is an informal process for deciding which integrated datasets get to be 303'd by geoconnex.us/theme/ vs by geoconnex.us/org/theme . Eventually seems like there should be actual rules around that.

**Comment by dblodgett-usgs** [comment]
pshhh rules... I'd prefer adhoc community governance. ;) 

Seems like we'll know it when we see it and, really, if someone wants a thematic redirect cool! Long run, I think having BOTH would be useful.

**Comment by ksonda** [comment]
agree having both kinds of redirects is fine. wrt rules/community governance, maybe there doesnt need to be a lot of fretting on who gets to contribute to geoconnex.us/dams, but there should be guidance around what? I guess? Looking at OpenStreetMap, I feel like we'd want to get a jump on [this kind of discussion](https://help.openstreetmap.org/questions/49216/is-a-dam-considered-a-building). At the early stage when we're working directly with people who are contributing I agree "i know it when i see it works" but I think it will come to a head eventually.

**Comment by dblodgett-usgs** [comment]
I agree re: getting ahead of discussions like that. 

I would hope that each thematic collection would have its own governance and not need to be dealt with here though (e.g. if we are going to create landing content for people's contributions). So we'd want to separate concerns of the PIDs and the creation of landing content.

So to summarize where we're at:

1. geoconnex.us will support thematic collection redirects on a case-by-case basis. 
1. if members of the thematic collections are also available from organizationally-managed name spaces, that is fine and it is handled with sameAs relations in meta-content.
1. rules or guidance for what actually goes into a given collection is out of scope for geoconnex.us and would be managed by a future project around generation of landing-content for a thematic collection.

**Comment by ksonda** [comment]
good summary, closing until thinking needs to be revised or elaborated
