### ISSUE TITLE
Add href from JSON to html template.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#137]
There is an href in the json for a collection. e.g. https://reference.geoconnex.us/collections/gages?f=json

But the html doesn't render that link. Maybe add it as a "More info" on the same line as the title?

This should also get added to the discovery app as well.

**Comment by ksonda** [comment]
need to add something like the relevant section from the stock template here

https://github.com/geopython/pygeoapi/blob/master/pygeoapi/templates/collections/collection.html#L62

to our template

https://github.com/internetofwater/geoconnex.us/blob/master/pygeoapi/pygeoapi-skin-dashboard/templates/collections/collection.html#L18

**Comment by ksonda** [comment]
@webb-ben if you have time could you take stab. I think we'd want to pipe in the href of the link tagged as "canonical" into a a label "(data source)" concatenated onto the title or [description](https://github.com/internetofwater/geoconnex.us/blob/master/pygeoapi/pygeoapi-skin-dashboard/templates/collections/collection.html#L18) element
