### ISSUE TITLE
Types of PIDs for geoconnex redirects.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#15]
I'm thinking about adding some guidance for what kinds of PIDs we will encourage/support to have registered. Am working on a [summary doc over here](https://docs.google.com/presentation/d/1tO8o9Tj0q10bqRlC6Ac7PzKXQ67Zwsxldm263DJ1bTA/edit?usp=sharing).

- Organizational monitoring or other information resources.
  - Provides stable identifiers for any organizations' resources.
  - Examples include: stream gages, wells, dam information, etc.
  - Redirect from `geoconnex.us/{org-namespace}/{org-path}` to `{org-url}`
  - Organizations own and maintain the PID list in this repo.
- Community reference locations.
  - Provides referenceable identifiers for shared surface water and groundwater locations.
  - Examples: NHD events, catchment indexes, groundwater wells.
  - Redirect from `geoconnex.us/{theme-namespace}/{id}` to `{community-system-url}`
  - A community actor or group would be required to curate these locations through some process managed outside this repository.
- Environmental feature of interest.
  - Provides referenceable identifiers for shared environmental features.
  - Examples: Reachcodes, comids, local aquifer ids.
  - Redirect from `geoconnex.us/{authority-namespace}/{authority-path}` to {community-canonical-url}
  - An authoritative community-oriented group would be expected to maintain these identifiers for the community.
- Established cataloging feature.
  - Provides referenceable identifiers for areal / place cataloging features.
  - Examples: hydrologic units, principle aquifers, counties, states. 
  - Redirect from `geoconnex.us/{authority-namespace}/{authority-path}` to `{community-canonical-url}`
  - An authoritative community oriented group would be expected to maintain these for the community.

Questions:
1. Is this taxonomy and the descriptions above 1) coherent and 2) complete enough to be a V1 guide?
1. Where should this material be added to the repository?

**Comment by ksonda** [comment]
1. It's mostly coherent, although I think there might be some remaining confusion about organizational vs. community reference locations, especially when "wells" is an example in both. I think it would be useful to have a complete working example system of PIDs in each of the groups, and possible a visualization of how such items would link to each other. 

2. I think the github wiki is fine. But we should also think about shopping presentations for conferences/meetings...maybe even <dread> an article?

**Comment by dblodgett-usgs** [comment]
Great point re: organizational resources vs community locations. I think the distinction between them is going to be clear when we have examples. The search of clear semantics and implementation patterns in this area is probably a fools errand. Each example is nuanced by business practice, history of bureaucracy, and history of engineering/scientific investigation on the ground. Given that, the diversity of ways that organizations information relate to some set of community-recognized reference locations is just going to be a mess we have to deal with case by case.

Regarding wells, an example is the National Groundwater Monitoring Network. It has a set of community reference locations that are wells. The contributor states and USGS have various web-resources that are about those reference locations. Both the NGWMN and the State/federal resources should have PIDs and would fall into the two distinct categories of organizational / community locations respectively. 

I slightly modified the descriptions above and put them [on the wiki.](https://github.com/internetofwater/geoconnex.us/wiki) as well as creating stubs for more about each of these categories.
