### ISSUE TITLE
skipGeometry parameter broken for /items/ api calls [general]

### ISSUE THREAD

**Issue by devincowan** [internetofwater/geoconnex.us#156]
API queries with the 
`skipGeometry`
parameter still contain all of the geometries in the response.
For example, look at the HU2 items:
https://reference.geoconnex.us/collections/hu02/items?f=json&lang=en-US&skipGeometry=true
The json still includes all of the geometries.

**Comment by ksonda** [comment]
@webb-ben this service is building from internetofwater/pygeoapi:latest

Any ideas? Something you changed for jsonld?

**Comment by ksonda** [comment]
it looks like skipGeometry is not implemented for the geopackage provider in geopython/pygeoapi, should port this issue to https://github.com/geopython/pygeoapi

**Comment by ksonda** [comment]
reported https://github.com/geopython/pygeoapi/issues/886

**Comment by devincowan** [comment]
thank you @ksonda

**Comment by ksonda** [comment]
fixed by https://github.com/geopython/pygeoapi/pull/887
