### ISSUE TITLE
reference feature finder process

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#160]
As more folks are starting to come on board, they are going to need an "easy" way to identify which reference features to use. For NHDPlusV2 comids/reachcodes, the NLDI point lookup endpoint may be suitable. For cataloging features, mainstems, and reference gages, some kind of other lookup will be necessary. 

One option is to have a web map, similar to the shiny app. But this requires a lot of manual looking around for each and every feature of interest. Another option I was thinking would be to have a pygeoapi process running on reference.geoconnex.us, where you could programmatically supply a lat/lon, and get a response of the members of every reference collection within a small bbox of the supplied lat/long.

e.g.

https://reference.geoconnex.us/processes/lookup?lon=x&lat=y

might return something like:

```
{
	"gages": [
		"https://geoconnex.us/ref/gages/1073686",
		"https://geoconnex.us/ref/gages/1185820"
	],
	"mainstems": "https://geoconnex.us/ref/mainstems/2600",
	"hu10": "https://geoconnex.us/ref/hu10/1802011101",
	"counties": "https://geoconnex.us/ref/counties/06061"

}
```

We could even possible have a https://reference.geoconnex.us/processes/lookup/map?lon=x&lat=y that would give you something like this

![image](https://user-images.githubusercontent.com/44071350/168860219-eb8fc725-2e83-43cf-bb88-4a4103eb1755.png)

**Comment by webb-ben** [comment]
Closed in lieu of https://github.com/internetofwater/geoconnex.us/issues/184

**Comment by webb-ben** [comment]
Closed in lieu of https://github.com/internetofwater/geoconnex.us/issues/184
