### ISSUE TITLE
[general] PWS collection items server error

### ISSUE THREAD

**Issue by devincowan** [internetofwater/geoconnex.us#165]
PWS returning 500
https://reference.geoconnex.us/collections/pws/items
![image](https://user-images.githubusercontent.com/17934193/183734769-2392db66-a0af-411a-9897-565b8d19743e.png)

**Comment by ksonda** [comment]
It's too big and the /items endpoint will probably not work anytime soon. I can provide a geopackage if desired, but imho you can leave this one off for now. Sorry it's a weird exception.

**Comment by devincowan** [comment]
No problem @ksonda, thanks for the info

**Comment by ksonda** [comment]
I need to figure out a solution to this sooner rather than later. gpkg of this size is too big maybe. One option is to use the esri feature service https://lincolninstitute.maps.arcgis.com/home/item.html?id=f3d10b6e8ad942ea8857410ddd4b0737 

Cons in CI/CD terms is the update process would have to be more manual.

Another alternative is to set up a separate pygeoapi server dedicated to pws that divides by state or something to use smaller gpkg, and then change the PID redirects

cons there is "reference.geoconnex.us" no longer includes "pws", but IDK how big of a deal that is

**Comment by dblodgett-usgs** [comment]
Could we setup a postgis loader for some of the bigger layers?

**Comment by ksonda** [comment]
Yeah we're exploring that

**Comment by mhweber** [comment]
@ksonda look forward to seeing where you land with this, was trying to pull in pws for work today and realized issue. Keep up the great work!

**Comment by ksonda** [comment]
@mhweber if you just want the data it's at this hydroshare resource item https://github.com/internetofwater/geoconnex.us/blob/d51a384f6c0cbde29d2c27bafed69de611e92859/pygeoapi/Dockerfile#L32

**Comment by mhweber** [comment]
Thanks @ksonda - I pulled it via hydroshare wfs - assume gets me to same data?

    wfs_pws <- "https://geoserver.hydroshare.org/geoserver/HS-20b908d73a784fc1a097a3b3f2b58bfb/wfs?"

    wfs_request <- "request=GetFeature&service=WFS&version=2.0.0&typeName=HS-20b908d73a784fc1a097a3b3f2b58bfb:temm&outputFormat=application/json"

    pws_wfs <- paste0(wfs_pws,wfs_request)
    pws <- st_read(pws_wfs)

**Comment by ksonda** [comment]
It would be the same data but I’ve never tried hydroshare wfs on a geopackage. I would just http GET the geopackage to a local file.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ksonda** [comment]
temm should have the same geometry but not necessarily all the descriptive attributes. ALso, in general ref_pws.gpkg is the most up-to-date file.

**Comment by martinseul** [comment]
currently HS does not have the ability to serve geopackages via it's connected Geoserver automatically. Only public geotiffs and shapefiles are accessible via WMS,WFS. This is something I'm considering as Geoserver can  read geopackages now.

**Comment by ksonda** [comment]
We have migrated to postgis so this should no longer be a problem
