### ISSUE TITLE
request with bbox parameter returns collection items that aren't otherwise returned [general]

### ISSUE THREAD

**Issue by devincowan** [internetofwater/geoconnex.us#170]
I noticed this morning that a request with bbox returns collection items that aren't returned in a more generic reqest.

For example, the following:
https://reference.geoconnex.us/collections/hu06/items/?bbox=-104.1504,46.6977,-114.7852,50.1375
returns a FeatureSet including the following item:
https://reference.geoconnex.us/collections/hu06/items/166

However, this request:
https://reference.geoconnex.us/collections/hu06/items/
doesn't include [pid166](https://reference.geoconnex.us/collections/hu06/items/166)

**Comment by dblodgett-usgs** [comment]
Possibly hitting a max feature count limit?

**Comment by ksonda** [comment]
1.) might be feature count, and have to iterate using parameters `startIndex` and `offset`
2.) and more likely in this case, is you're using the fid to populate the /items/{id} when you should be using the {id} field

there is no https://reference.geoconnex.us/collections/hu06/items/166, you probably mean https://reference.geoconnex.us/collections/hu06/items/090400

**Comment by devincowan** [comment]
Thanks for the correction on `fid` Kyle--you're right.
However, my actual issue was indeed in thinking a request like
https://reference.geoconnex.us/collections/hu06/items?f=json
would return all hu06 items. I see now that the default is to return the first 100 items.

Thanks!
