### ISSUE TITLE
[general] Feature "NAME" field does not match schema "name"

### ISSUE THREAD

**Issue by devincowan** [internetofwater/geoconnex.us#178]
Let's grab the jsonld for a single HU02 using [https://reference.geoconnex.us/collections/hu02/items?f=jsonld&lang=en-US&limit=1&properties=name&skipGeometry=true&offset=0](https://reference.geoconnex.us/collections/hu02/items?f=jsonld&lang=en-US&limit=1&properties=name&skipGeometry=true&offset=0)

```
{
  "@context": [
    {
      "schema": "https://schema.org/",
      "type": "@type",
      "features": "schema:itemListElement",
      "FeatureCollection": "schema:itemList"
    },
    {
      "schema": "https://schema.org/",
      "NAME": "schema:name",
      "gnis_url": {
        "@id": "schema:subjectOf",
        "@type": "@id"
      }
    }
  ],
  ...REDACTED...
}
```
Note the `"NAME": "schema:name",`

Now query a single object for json using https://reference.geoconnex.us/collections/hu02/items?f=json&lang=en-US&limit=1&properties=name&skipGeometry=true&offset=0
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "New England Region"
      },
      "id": "01",
      "geometry": null
    }
  ],
  "numberMatched": 22,
  "numberReturned": 1,
    ...REDACTED...
}
```
note the `"name": "New England Region"`

The issue is that `name` not = `NAME`

This is true for other collections in addition to HU02

**Comment by dblodgett-usgs** [comment]
erp -- this is a miss -- @ksonda we need to switch all the json-ld to lowercase now that we are using postgis?

**Comment by ksonda** [comment]
2 issues here. one is that yes, need to change all the configs to all lower case, will get on that

But, the jsonld format passed to an /items endpoint will only return an itemlist with {"@id": "http uri", "@type":"Place"}

**Comment by ksonda** [comment]
#179 fixes

**Comment by devincowan** [comment]
Mighty speedy, thanks @ksonda verified our implementation which consumes your service is functional again
