### ISSUE TITLE
HU02 Regex Request

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#18]
I think making these explicit for 2-digit, 4-digit, etc. is going to give us the most flexibility.

## Contact Information
Your name: dblodgett

Your email: dblodgett@usgs.gov

Your organization: USGS

Your organization website: https://labs.waterdata.usgs.gov/

### The base PID pattern you would like 
(e.g. https://geoconnex.us/example-namespace/features/)

PID pattern: https://geoconnex.us/ref/hu02/##

### The desired target URI base pattern 
(e.g. https://example.org/features?query=)

Target pattern: https://info.geoconnex.us/collections/hu02/items/##

### Explanation of the kinds of expressions to match from the end of the PID pattern to the end of the target pattern.

Expression type: 
- `^/ref/hu02/([0-9]+).*$`
- `https:/info.geoconnex.us/collections/hu02/items/$1`

### 2-3 example target URIs 

target URI example: https:/info.geoconnex.us/collections/hu02/items/01

Target URI example: https:/info.geoconnex.us/collections/hu02/items/20

**Comment by ksonda** [comment]
Minted, but will probably change if we figure out #19

**Comment by dblodgett-usgs** [comment]
Rushed the issue above a bit too much. 

Was thinking we'd do this at `https://geoconnex.us/ref/hu02/##` but see that I made that decision half way through making the issue.

Why don't we switch to declaring these explicitly rather than a regex? I'm much more comfortable with being explicit where we can be. 

Will check in an updated hu02 layer and the csv / xml in a while if that's cool with you?

**Comment by dblodgett-usgs** [comment]
OK -- much more explicit about this now. I'll open a PR.
