### ISSUE TITLE
pygeoapi cannot use PIDs as json-ld @id

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#19]
Pygeoapi basically works as a way to generate landing content and json-ld representation thereof. see [https://info.geoconnex.us](https://info.geoconnex.us/collections/hu02/items)

However, for feature collections pygeoapi generates landing pages (and json-ld **@id**) at 

info.geoconnex.us/**collections**/[feature_collection_name]/**items**/[feature-id]

when we need it to be 

geoconnex.us/[feature_collection_name]/[feature-id]

From where I stand, some options to use pygeoapi in a SELFIE way are:

1. Require all landing content generated at pygeoapi to mint PIDs of the pattern geoconnex.us/**collections**/[feature_collection_name]/**items**/[feature-id]
, and modify pygeoapi configuration so the base url is https://geoconnex.us. This I would call the "hacky" way, and only suitable for "community" content to avoid confusion about organizations with similar feature collection names (e.g. wells, stations, etc.)

2. Modify pygeoapi so that it generates json-ld @id of format [hostname]/[feature_collection_name]/[feature-id]. This is the proper way but will require serious investment in generating issues at github/pygeoapi or forking it. I think [this](https://github.com/geopython/pygeoapi/blob/3debd0c750e3f0b41f57298f83f2b92c2e046bba/pygeoapi/linked_data.py) (lines 125ish and 178ish) is the minimum piece that would need to be modified.  Doing so might break other things that we may or may not care about as long as we have PIDs redirecting to the correct URLs that have the /collections/xxx/items/xxx structure.

**Comment by dblodgett-usgs** [comment]
Option 2 is very much what we want to do. 

Line 178 is where we need to hack in a non-information URI. The way I could see doing it is in the json-ld configuration, if there is an `@id` declared, then that attribute gets used to override.

In the hu02 geojson that is in so far, that is a "uri" attribute. So we would add: `uri: "@id"` and figure out how to pick up that configuration up and use it as an override at line 178.

Maybe we know someone who would be willing to implement and PR?

**Comment by ksonda** [comment]
I don't know enough to want to mess with conditions. Im taking on a student who's pretty good at python on May 11 who can take a crack.

Alternatively, maybe we can have a ```namespace:``` specification in the ```resource:``` part of the config.yml that replaces "collections" in Line 178. And we just take "/items/" out.

**Comment by ksonda** [comment]
For now addressed [here](https://github.com/ksonda/pygeoapi/blob/master/pygeoapi/linked_data.py) with this hack which will work if the data has a field exactly 'uri'. 

docker image internetofwater/pygeoapi-geoconnex:latest

```python
uri = data['properties'].get('uri')
    if identifier and uri:
        data['id'] = '{}'.format(uri)
    elif identifier: 
        data['id'] = '{}/collections/{}/items/{}'.format(config['server']['url'],dataset,identifier)
    else:
        data['id'] = '{}/collections/{}/items'.format(config['server']['url'],dataset)
```

This results in the json-ld media type for the collective landing pages breaking, although the individual feature items work correctly. Compare:

- https://info.geoconnex.us/collections/hu02/items?f=jsonld
- https://info.geoconnex.us/collections/hu02/items/12?f=jsonld

I'm sure it breaks a ton of other stuff, at least Travis CI tells me so. Hopefully will be addressed here : [https://github.com/geopython/pygeoapi/issues/433](https://github.com/geopython/pygeoapi/issues/433)
