### ISSUE TITLE
Deploy pids.geoconnex.us from its repository

### ISSUE THREAD

**Issue by webb-ben** [internetofwater/geoconnex.us#197]
PID-Service does not really fit into this repository. We should consider providing a redirect to https://github.com/internetofwater/pids.geoconnex.us and deploy the PID service from there. The chain should still be initiated by a commit to the namespaces folder in this repository, but pids.geoconnex.us should handle its build and deployment.

**Comment by ksonda** [comment]
I'm fine with rationalizing the ci/cd however you see fit, as long as we're still administering community pid contributions from this repo for the time being
