### ISSUE TITLE
Deploy reference.geoconnex.us from its repository

### ISSUE THREAD

**Issue by webb-ben** [internetofwater/geoconnex.us#199]
In the same spirit at #197, is there a reason reference features are deployed `/pygeoapi`? Could https://github.com/internetofwater/geoconnex.us/tree/master/pygeoapi just be the be the seed for https://github.com/internetofwater/reference.geoconnex.us?

**Comment by ksonda** [comment]
Related, changes to pygeoapi config yml should trigger a whole reference data database rebuild I suppose. Changes to templates should only trigger rebuilt of pygeoapi.
