### ISSUE TITLE
pygeoapi wishlist

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#21]
A wishlist for pygeoapi in rough order of priority> Probably most efficient to run these on a fork.  [https://github.com/ksonda/pygeoapi](https://github.com/ksonda/pygeoapi) builds docker ```internetofwater/pygeoapi-geoconnex:latest```

- [x] allow geoconnex.us PIDs (#19 )

- [ ] add some minimal links to community resources automatically

- [x] remove unnecessary elements from landing page

- [x] make snazzy geoconnex branding to replace pygeoapi logos

**Comment by ksonda** [comment]
Pretty sure the landing page (including STAC) can be modified easily [here](https://github.com/geopython/pygeoapi/blob/c151579991561c562baf4969621b479998f34453/pygeoapi/templates/root.html)

**Comment by dblodgett-usgs** [comment]
I did not. Can we copy an updated template in when we start Docker up the same way we do the configuration? Would be good to make some other modifications there.

Do you or someone else on the IoW team want to take on most of this? I think #19 is probably going to require a PR to pygeoapi or we should run a fork.

**Comment by ksonda** [comment]
just mapping the root.html volume didn't work. Building my own docker image did though. 

```
docker pull internetofwater/pygeoapi-geoconnex:latest
```

**Comment by ksonda** [comment]
for the time being, addressed by #60
