### ISSUE TITLE
COMID and HUC12 identifiers from NHDPlusV2

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#24]
## Contact Information
Your name: Dave Blodgett

Your email: dblodgett@usgs.gov

Your organization: USGS

Your organization website: labs.waterdata.usgs.gov

### The base PID pattern you would like 

PID pattern:
https://geoconnex.us/nhdplusv2/comid/####
https://geoconnex.us/nhdplusv2/huc12/####

### The desired target URI base pattern 

Target pattern:
https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/####
https://labs.waterdata.usgs.gov/api/nldi/linked-data/huc12pp/####

### Explanation of the kinds of expressions to match from the end of the PID pattern to the end of the target pattern.

Expression type: Can just match any number of numbers. 
e.g. for comid, it's a large integer so this would work:  
`^/nhdplusv2/comid/([0-9]+).*$`  
`https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/$1`

e.g. for huc12s it's a 12-digit character string so this would work:  
`^/nhdplusv2/huc12/([0-9]+).*$`  
`https://labs.waterdata.usgs.gov/api/nldi/linked-data/huc12pp/$1`. 

### 2-3 example target URIs 

target URI example:
https://geoconnex.us/nhdplusv2/comid/13293376
https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/13293376

Target URI example:
https://geoconnex.us/nhdplusv2/huc12/070101010101
https://labs.waterdata.usgs.gov/api/nldi/linked-data/huc12pp/070101010101

**Comment by dblodgett-usgs** [comment]
Seems a little funny to have the huc12s be in an nhdplusv2 namespace, but there is a version of huc12s that is stable in the NHDPlusV2 database that we use a lot. This is intended to point to those. 

Once these are in, I'll work up a readme that explains that.

**Comment by ksonda** [comment]
just confirming you want the pour points and not the boundaries?

**Comment by dblodgett-usgs** [comment]
We need better HUC12 langing pages that would have the boundaries as their preview geometry in the future -- but we don't have that right now. The pour points will work for the time being.
