### ISSUE TITLE
Searchable PID catalog

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#34]
It might be useful to have a user-friendly, searchable CKAN/Socrata-like PID catalog that harvests automatically from this repository,

One option is [JKAN](https://jkan.io/), where metadata is harvested from .yaml files in github and then uses Jekyll to render the pages as GitHub pages with some elasticsearch capability. If we were a bit more structured with the PID request process, this could be automated for 1:1 requests. regex ones would probably have to be manually managed.

**Comment by dblodgett-usgs** [comment]
I'd say we should go there is we end up drowning in PIDs? This process we have should work reasonably well for now.
