### ISSUE TITLE
'uri' vs 'id' field

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#36]
For PID submission we require 'id', pygeoapi hack requires 'uri' for now. Maybe its minor, but maybe both should be 'uri'. Will require changes README here and to pidsvcBackup.

**Comment by dblodgett-usgs** [comment]
Oh, maybe. I can allow uri or id in the R package to make it easy?

**Comment by ksonda** [comment]
addressed by #60
