### ISSUE TITLE
Hydrologic unit reference units.

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#37]
I got the HU02 layer in as something of a test. We also need HU04, and HU08. I'm not convinced there's value in the 06 and 12 and will hold off on adding those for now. 

My plan is to use these units as they are declared in the latest WBD. The HU08 layer may change over time, but we'll deal with that as it happens.

**Comment by ksonda** [comment]
Can we also do HU10? DOE has a data service they want to play that is primarily about HUC10s.
