### ISSUE TITLE
Administrative/ Census Geographies

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#41]
I'll start thinking about Census geographies for stuff that doesn't change between Decennial Census rounds that I've seen organize hydro information. US Census operates TigerWEB, an ESRI REST service, it's not very referenceable. For now we'll host these at info.geoconnex.us, but maybe evenutally we can get US Census to play ball. Anyway, PID patterns, all 1:1:

- **Census Divisions** /ref/division/[GEOID]
- **Census Regions** /ref/regions/[GEOID]
- **States**  /ref/state/[GEOID]
- **Counties** /ref/county/[GEOID] 
- **American Indian/Alaka Native Areas/ Hawaiian Home lands** /ref/aiannh/[GEOID]
- **Metro Statistical Areas** /ref/msa00/[GEOID] and /ref/msa10/[GEOID] (changes decennial census)
- **Urbanized Areas** /ref/ua00/[GEOID] and /ref/ua10/[GEOID] (changes decennial census)

Should any of these be removed? added to? namespace different?

**Comment by dblodgett-usgs** [comment]
I'm not really familiar with census units myself. Can we add these as needed or need to go ahead and create them all now?

**Comment by ksonda** [comment]
I’m fine adding what’s on this list and won’t be broken up about it if they’re not needed. I’m fairly confident this set covers the type of thing we’d want census to do. I’ll ask some water economists at EPA and USDA I know to see what they think would be important, if anything.
