### ISSUE TITLE
PIDs in new info.geoconnex layers?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#49]
@ksonda -- can we add PIDs using the "uri" pattern to those features so they are discoverable?

Would be nice if we had a configuration to do it but at the least you can just add the URIs the way I have with the other layers?

**Comment by dblodgett-usgs** [comment]
Oh funny -- they are there. I just don't see them in this view: https://info.geoconnex.us/collections/ua10/items

I guess that's probably ok to leave it as is.

**Comment by ksonda** [comment]
Confused, compare https://info.geoconnex.us/collections/hu04/items/0315
and https://info.geoconnex.us/collections/states/items/12

Both have 'uri'. Do you mean move 'uri' up to be a higher-order column so it shows up here: https://info.geoconnex.us/collections/states/items
