### ISSUE TITLE
Regex Redirect Threshold

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#56]
The 83 CUAHSI providers added (the not-large ones) amount to ~115k PIDs. This wasn't terrible to write code for that chops it up into 2000-row units and POSTs (especially with a [post_pids() function](https://github.com/ksonda/IoW-PIDsvc/blob/pidsvcBackup/pidsvcBackup/R/post_pids.R) added to R package), and it took ~20 minutes. I don't think it's too bad for the limit to basically be 100MB rather than 10,000 if the benefits of 1:1 outweighs a loop/sapply every now and again

**Comment by dblodgett-usgs** [comment]
I'm fine with that. Being explicit is good if people will tolerate it.
