### ISSUE TITLE
QueryString formatting

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#57]
We've been asking for QueryStrings for content types that look like ```f?=.*```

For some reason, this means that GET requests without ```?f=anything``` are redirected to ones with ```?f=``` appended. I don't know if this is bad, but it seems unclean. 

If you change the QueryString to ```f=.*``` you get normal behavior

For example: ```https://geoconnex.us/ref/hu02/02``` -> 303```https://info.geoconnex.us/collections/hu02/items/02?f=```

changing f?=.* to f=.* : ```https://geoconnex.us/ref/hu02/01``` -> 303```https://info.geoconnex.us/collections/hu02/items/01```

I don't know if this breaks anything. I wonder if it has to do with the pygeoapi index issues we have been having (because what google infers the canonical URL to be based on all the alternate links doesn't exactly match what is redirected to). 

Sad: have to change A LOT of PIDs
Happy: Can write something that recursively does all csvs and xml in the repo

Priority: lower than the main pygeoapi PRs that Greg is working on

**Comment by dblodgett-usgs** [comment]
dang -- that's my bad. Easy to correct the regex ones. I'll fix the ones I created over in geoconnex_prep.

**Comment by ksonda** [comment]
Checked in corrections to /ref/ PIDs. Leaving CUAHSI for the remainder of #55
