### ISSUE TITLE
Automatic context/ json-ld generation?

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#6]
Maybe if lat/lon is provided, the service can automatically st_intersect with HUC12, and generate a minimal json-ld context and content for every entry. Maybe there should be a separate project that does that to assist newcomers to landing pages/SELFIE ideas.

**Comment by dblodgett-usgs** [comment]
Do you want to stand up a parallel geoconnex.us/info that would host said static content for people who don't have landing pages of their own?

**Comment by ksonda** [comment]
Could be a paralell repo, or we could put /info subdirectories in every namespace directory. Balance between parsimony for users vs. worker code I guess.

**Comment by ksonda** [comment]
Per our slack conversation, could be based off your work:

here: https://github.com/opengeospatial/SELFIE/tree/master/tools/R

and

here: https://github.com/dblodgett-usgs/chyld_pilot_data_prep

**Comment by dblodgett-usgs** [comment]
If this is something you want to pursue -- I just got some news that means I have a little more bandwidth than expected and would be game to start building the page-generation code. 

Building nice-looking and nice-functioning HTML pages with a little embedded JS would be an area I would need help, but the data integration and JSON-LD generation would be pretty straight forward for a bunch of baseline data.

**Comment by ksonda** [comment]
We have our semi-annual board meeting tuesday where the staff is pitching a couple of possible big pushes we could do in the next 1-2 years. geoconnex and other "aid to data stewards for linked-data" is among the items. If I get a go ahead to make that area a priority I can be up to pursue for sure. Lauren might be better placed to do some nice JS work though. There's also a ton of recently defunded Duke grad students around I might be able to nab if there's web dev skills among them.

**Comment by ksonda** [comment]
I'm just not clear on the need yet. I have a gut feeling it might be a nice thing to have in our back pocket for orgs that are "linked data sounds great, fully support, don't have the bandwidth right now". But I could be wrong. What's the marginal benefit you think over a focus on finding other big willing players like CUAHSI, WaDE, UFOKN and doing a minimum working meta information registry?

**Comment by dblodgett-usgs** [comment]
I think that keeping the core stuff in a non-organizational space and supported by the community would be beneficial from a willingness to contribute perspective. Need to think on it a little more.

**Comment by ksonda** [comment]
I can see the argument for us hosting such things for "core stuff" a la #12, in which case this issue can be combined with #12. 

Hosting 'organizational' stuff on behalf of organizations would then be possible but we can push the decision on whether to institutionalize that down quite a ways.

**Comment by dblodgett-usgs** [comment]
I think we are close to being able to close both of these for the time being. This issue is going to be a good chunk of work that we'd want to plan out more diligently and #12 is really just setting up a regex redirect for thematic collections as far as this repo is concerned, right?

**Comment by ksonda** [comment]
Can close for now. Should note it is possible DOE is interested in funding something like this, which if it was, would be available starting around october.
