### ISSUE TITLE
[regex redirect request]

### ISSUE THREAD

**Issue by dyoung440** [internetofwater/geoconnex.us#65]
## Contact Information
Your name: Dwane Young

Your email: young.dwane@epa.gov

Your organization: U.S. EPA

Your organization website: https://mywaterway.epa.gov

### The base PID pattern you would like 
(e.g. https://geoconnex.us/example-namespace/features/)

PID pattern: https://geoconnex.us/epa/hmw/

### The desired target URI base pattern 
(e.g. https://example.org/features?query=)

Target pattern: https://mywaterway.epa.gov/community/{NHDPlusHuc12}/overview

### Explanation of the kinds of expressions to match from the end of the PID pattern to the end of the target pattern.
(e.g. 9-digit numbers, 12-character alphanumeric strings, specific combinations of letters & numbers & special characters)

Expression type: Replace {NHDPlusHuc12} with actual HUC12 number, including leading '0s'

### 2-3 example target URIs 
(e.g. https://example.org/features?query=12345)

target URI example: https://mywaterway.epa.gov/community/020700110204/overview

Target URI example: https://mywaterway.epa.gov/community/051302020304/overview

**Comment by ksonda** [comment]
addressed by #66
