### ISSUE TITLE
Licensing for geoconnex.us?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#78]
Is there any issue labeling this repo and pretty much everything geoconnex.us-related with a CC0 license?

**Comment by ksonda** [comment]
I think it's murky on IoW end whether we want to preclude the possibility of someone somewhere making some proprietary value add, so MIT license would be safer. If public agency participation is easier if its all public domain then that's important to consider.

**Comment by dblodgett-usgs** [comment]
It's pretty fundamental that this be a public domain project. I wouldn't be able to justify my contribution without an ethics exception if it were anything but public domain. Probably a bigger conversation, but geoconnex.us in general needs to remain completely neutral and public domain.

**Comment by ksonda** [comment]
Fair enough. CC0 it is.
