### ISSUE TITLE
Geoconnex and National Hydrographic Infrastructure

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#83]
Had an interesting conversation with Dwane and Emily, where they implied there's general confusion about how coordinated IoW and NHI activities are. My sense is if there is any coordination, it's through geoconnex. My purpose for this issue is to organize discussions about that. An immediate pressing one I think we should start sussing out: what should the technical and/or social process interactions between geoconnex and the NLDI be?

**Comment by dblodgett-usgs** [comment]
![image](https://user-images.githubusercontent.com/1492803/97183974-64cd1200-176c-11eb-8cc4-6e4d2c9841b6.png)

Is a good architectural summary from the NHI side. 

Given that everything is a moving target, I am not sure there are things that are worth formalizing on the technical side. I think it would possibly be worth formalizing some roles and responsibilities (social) between the two initiatives. Having some roles might help us identify gaps or at least identify people who should be on point to identify them.

**Comment by ksonda** [comment]
more discussions on this incoming. Peters setting up a bunch of meetings with ever expanding groups of people at fed agencies involved with NHI. Here was my first straw man at geoconnex/NHI connection points shown to Emily, Dwane, Michelle. Emily adamant that Roland be brought into convos ASAP.
[Geoconnex and NHI.pptx](https://github.com/internetofwater/geoconnex.us/files/6015121/Geoconnex.and.NHI.pptx)

**Comment by ksonda** [comment]
closing this pending developing conversations with NHI people and other federal roundtable participants
