### ISSUE TITLE
USGS Monitoring Location

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#85]
## Contact Information
Your name: Dave Blodgett
Your organization: USGS
Your organization website: https://waterdata.usgs.gov/nwis

### The base PID pattern you would like 
PID pattern:

```
https://geoconnex.us/usgs/monitoring-location/
```

### The desired target URI base pattern 
Target pattern:

```
https://waterdata.usgs.gov/monitoring-location/
```

### Explanation of the kinds of expressions to match from the end of the PID pattern to the end of the target pattern.
(e.g. 9-digit numbers, 12-charachter alphanumeric strings, specific combinations of letters & numbers & special characters)

Expression type: any number of alphanumeric characters

### 2-3 example target URIs 

target URI example: https://waterdata.usgs.gov/monitoring-location/08383500
Target URI example: https://waterdata.usgs.gov/monitoring-location/05428500

**Comment by ksonda** [comment]
do you want this to pass through stuff like #parameterCode=00060

**Comment by dblodgett-usgs** [comment]
Not initially. We can add stuff as it's really needed?
