### ISSUE TITLE
/ref/dams

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#90]
@mikejohnson51 and I are discussing incorporating the UFOKN NID/ORNL/OSM features as ref/dams. 

We came upon a similar conceptual issue to #81 , where the UFOKN features include associations between the dams and the relevant NHD waterbody ID. Working through this here could be helpful for how to model other impoundment/diversion/hydrometricStation-storage relationships that are likely to come up with WaDE, USBR, USDOE Hydropower, and various state datasets IoW is starting to wrangle.  There's no landing content for waterbodies though. 

@dblodgett-usgs (at your LEISURE)...any opinions on making /ref/waterbodies, living at [info.geoconnex.us](https://info.geoconnex.us), populated with the NHDPlusV2 versions for now?

**Comment by ksonda** [comment]
per @mikejohnson51, UFOKN leadership doenst want to publish features until beta launch in ~6 months. womp womp.

Other thought. Should UFOKN mint geoconnex ids for all their urban features? If so, what distinguishes the UFOKN graph from a subgraph of the geoconnex graph?

**Comment by dblodgett-usgs** [comment]
Only if minting all those IDs in a public space is useful? Seems like a lot.

Re: waterbodies. Maybe. We need to take on waterbodies for a few projects but I want to get mainstems under the belt first.

**Comment by ksonda** [comment]
agree. now with UFOKN less applicable, there needs to be ref_dams open source project with NID as an anchor dataset. OSM and SWOT/SWORD as immediate complements come to mind.

**Comment by mikejohnson51** [comment]
also check: https://zenodo.org/record/5793918#.YdzCedbMKDU

**Comment by ksonda** [comment]
I dont have a particular problem with that as long as that repo is under some kind of CC share/share-alike license or public domain and is forkable. @dblodgett-usgs you may have stronger opinions

**Comment by mikejohnson51** [comment]
Sure, we have no guidance on licensing so that a-ok.

**Comment by ksonda** [comment]
https://github.com/internetofwater/ref_dams
