### ISSUE TITLE
pygeoapi URI refactor

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#93]
@webb-ben has been working on bringing our desired pygeoapi up to date with master [here](https://github.com/webb-ben/pygeoapi)

I need to set up a demo server that deploys his emerging solution with some id/uri specification scenarios to assist with PR review  (and hopefully merge)

**Comment by ksonda** [comment]
@webb-ben, can you please move your modifications to a fork of geopython/pygeoapi rather than of internetofwater/geoconnex.us ?

**Comment by ksonda** [comment]
Below is a table of id/uri specification scenarios by implementation, comapring the pygeoapi master branch, the geoconnex branch, and @webb-ben 's updated geoconnex branch.


row|pygeoapi branch|scenario|example item link|jsonld playground  flattened|
|-|-----------------|----------|------------------|----------------------------|
|1|master               |  @id is api, id is 'id'          |https://pygeoapi-master.internetofwater.dev/collections/obs_id_id/items/371 |                            https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-master.internetofwater.dev%2Fcollections%2Fobs_id_id%2Fitems%2F371%3Ff%3Djsonld&context=%7B%7D|
|2|master               |   @id is api, id is not 'id'        |https://pygeoapi-master.internetofwater.dev/collections/obs_id_name/items/obs%20371 |                           https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-master.internetofwater.dev%2Fcollections%2Fobs_id_name%2Fitems%2Fobs%2520371%3Ff%3Djsonld&context=%7B%7D |
|3|current geoconnex|  @id is api, id is 'id'         |https://pygeoapi-geoconnex.internetofwater.dev/collections/obs_id_id/items/371 | https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-geoconnex.internetofwater.dev%2Fcollections%2Fobs_id_id%2Fitems%2F371%3Ff%3Djsonld&context=%7B%7D |
|4|current geoconnex|  @id is api, id is not 'id'             |https://pygeoapi-geoconnex.internetofwater.dev/collections/obs_id_name/items/obs%20371 |  https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-geoconnex.internetofwater.dev%2Fcollections%2Fobs_id_name%2Fitems%2Fobs%2520371%3Ff%3Djsonld&context=%7B%7D |
|5|current geoconnex|  @id is PID, id is 'id'        |https://pygeoapi-geoconnex.internetofwater.dev/collections/obs_id_id_uri/items/371 | https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-geoconnex.internetofwater.dev%2Fcollections%2Fobs_id_id_uri%2Fitems%2F371%3Ff%3Djsonld&context=%7B%7D|
|6|current geoconnex |  @id is PID, id is not 'id'         |https://pygeoapi-geoconnex.internetofwater.dev/collections/obs_id_name_uri/items/obs%20371 |  https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-geoconnex.internetofwater.dev%2Fcollections%2Fobs_id_name_uri%2Fitems%2Fobs%2520371%3Ff%3Djsonld&context=%7B%7 |
|7|@webb-ben           |   @id is api, id is 'id'           |https://pygeoapi-uri-pr.internetofwater.dev/collections/obs_id_id/items/371 |                             https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-uri-pr.internetofwater.dev%2Fcollections%2Fobs_id_id%2Fitems%2F371%3Ff%3Djsonld&context=%7B%7D |
|8|@webb-ben           |   @id is api, id is not 'id'          |https://pygeoapi-uri-pr.internetofwater.dev/collections/obs_id_name/items/obs%20371 |https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-uri-pr.internetofwater.dev%2Fcollections%2Fobs_id_name%2Fitems%2Fobs%2520371%3Ff%3Djsonld&context=%7B%7D |
|9|@webb-ben           |   @id is PID, id is 'id'         |https://pygeoapi-uri-pr.internetofwater.dev/collections/obs_id_id_uri/items/371 | https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-uri-pr.internetofwater.dev%2Fcollections%2Fobs_id_id_uri%2Fitems%2F371%3Ff%3Djsonld&context=%7B%7D | 
|10|@webb-ben           |   @id is PID, id is not 'id'           |https://pygeoapi-uri-pr.internetofwater.dev/collections/obs_id_name_uri/items/obs%20371 | https://json-ld.org/playground/#startTab=tab-flattened&json-ld=https%3A%2F%2Fpygeoapi-uri-pr.internetofwater.dev%2Fcollections%2Fobs_id_name_uri%2Fitems%2Fobs%2520371%3Ff%3Djsonld&context=%7B%7 |

**Comment by ksonda** [comment]
@dblodgett-usgs and I should write up the desired behavior we want and submit it to pygeoapi issue.

I think what we want, is for there to be a boolean configuration option under ```resource:``` called ```geojsonld:``` whose default value is ```true```. When it is ```false```, we want the json-ld option to behave in the following manner:

1. No geojsonld context, only what is manually specified in the ```context:``` configuration
2. No ```properties``` block. All attributes should be the same level as ```@id```  

any other changes we want?

**Comment by dblodgett-usgs** [comment]
Yep -- this is the desired behavior. 

No geometry unless it's point since it breaks jsonLD rules.

I think it's an error condition if there are conflicts with the id attribute.

Current:
```json
{
	"@context": [
		{
			"schema": "https://schema.org/",
			"geojson": "https://purl.org/geojson/vocab#",
			"Feature": "geojson:Feature",
			"FeatureCollection": "geojson:FeatureCollection",
			"Point": "geojson:Point",
			"bbox": {
				"@container": "@list",
				"@id": "geojson:bbox"
			},
			"coordinates": {
				"@container": "@list",
				"@id": "geojson:coordinates"
			},
			"features": {
				"@container": "@set",
				"@id": "geojson:features"
			},
			"geometry": "geojson:geometry",
			"id": "@id",
			"properties": "geojson:properties",
			"type": "@type"
		},
		{
			"schema": "https://schema.org/name",
			"name": "schema:name",
			"description": "schema:description",
			"subjectOf": {
				"@id": "schema:subjectOf",
				"@type": "@id"
			}
		}
	],
	"type": "Feature",
	"geometry": {
		"type": "Point",
		"coordinates": [
			-85.3199473,
			33.22511878
		]
	},
	"properties": {
		"fid": 1,
		"id": "https://geoconnex.us/ref/gages/1029567",
		"uri": "https://geoconnex.us/ref/gages/1029567",
		"name": "WEHADKEE CREEK NEAR PITTMAN AL",
		"description": "USGS NWIS Stream/River/Lake Site 02339210: WEHADKEE CREEK NEAR PITTMAN AL",
		"subjectOf": "https://waterdata.usgs.gov/monitoring-location/02339210",
		"provider": "https://waterdata.usgs.gov",
		"provider_id": "02339210",
		"nhdpv2_REACHCODE": "03130002000353",
		"nhdpv2_REACH_measure": 9.594026996679105,
		"nhdpv2_COMID": 3291414
	},
	"id": "https://geoconnex.us/ref/gages/1029567"
}
```
Desired:
```json
{
	"@context": [
		{
			"schema": "https://schema.org/",
			"id": "@id",
			"type": "@type",
			"name": "schema:name",
			"description": "schema:description",
			"subjectOf": "schema:subjectOf"
		}
	],
	"type": "Feature",
	"fid": 1,
	"id": "https://geoconnex.us/ref/gages/1029567",
	"uri": "https://geoconnex.us/ref/gages/1029567",
	"name": "WEHADKEE CREEK NEAR PITTMAN AL",
	"description": "USGS NWIS Stream/River/Lake Site 02339210: WEHADKEE CREEK NEAR PITTMAN AL",
	"subjectOf": "https://waterdata.usgs.gov/monitoring-location/02339210",
	"provider": "https://waterdata.usgs.gov",
	"provider_id": "02339210",
	"nhdpv2_REACHCODE": "03130002000353",
	"nhdpv2_REACH_measure": 9.594026996679105,
	"nhdpv2_COMID": 3291414
}
```

**Comment by ksonda** [comment]
in your "desired" you left out geometry altogether even though this is a point. Intentional?

**Comment by dblodgett-usgs** [comment]
I dropped it since it uses the geojson context. I'm fine leaving it in, but I'm not really sure it adds THAT much. If we were to add them back, it would be more useful to encode as a schema:geo object?

**Comment by ksonda** [comment]
```it would be more useful to encode as a schema:geo object?``` agreed or geosparql/wkt? I guess for pygeoapi purposes probably schema:geo

**Comment by webb-ben** [comment]
@dblodgett-usgs  I have a working version that creates your desired JSON-LD. The issue with using `"id": "@id"` is that pygeoapi uses `'id'` field as its internal reference to the item. Changing the `'id'` to make the JSON-LD work results in a wonky html page (either two id fields in the properties block, or the uri as the name of the item). 

I'm happy to share more details but it might be a bit too verbose for this thread.

**Comment by dblodgett-usgs** [comment]
Great! What's the next step then?

**Comment by ksonda** [comment]
@webb-ben , you showed me two scenarios.

 (1) where you our routing `id` that is `id_field` to the html templates : 
 
![image](https://user-images.githubusercontent.com/44071350/113862880-fa86b780-9776-11eb-9196-567e2e2b6532.png)



(2) where routing `id` that is `uri_field` to the html templates
![image](https://user-images.githubusercontent.com/44071350/113862911-02465c00-9777-11eb-8847-895638f6a3ae.png)


At first glance, (2) I think is closer to what we want

Questions: 
- What is the canonical url in the html in each of these scenarios? We want it to be the `id` from `uri_field:` 
- Supposing we work from Scenario (2), is there a way to move that `id` up from the bottom and rename it "URI" in the html?

**Comment by webb-ben** [comment]
The canonical URL in both situations is https://geoconnex.us/ref/gages/1029567. If uri_field is not specified it would become http://[HOSTNAME]/collections/gages/items/1029567. 

I will look into the order of the entries... I think we would have to use ordered dictionaries. Should be easy enough!

**Comment by webb-ben** [comment]
Is there ever a case where geojsonld will be enabled but uri_field is not specified? If they won't always be used together, what should the difference in their behaviors be? If they always will be used together do we need to declare both?

**Comment by ksonda** [comment]
If it's not a huge issue I'd say to let them vary independently.

**Comment by webb-ben** [comment]
uri_field affects what will end up as the cannonical URL, and what is set as `id` in the json-ld. geojsonld affects the format of the json-ld and html.

```
uri_field=uri, geojsonld=True
{
  "@context": [
    {
      "schema": "https://schema.org/name",
      "id": "@id",
      "type": "@type",
      "name": "schema:name",
      "description": "schema:description",
      "subjectOf": "schema:subjectOf"
    }
  ],
  "type": "Feature",
  "pygeoapi_id": 1029567,
  "fid": 1,
  "uri": "https://geoconnex.us/ref/gages/1029567",
  "name": "WEHADKEE CREEK NEAR PITTMAN AL",
  "description": "USGS NWIS Stream/River/Lake Site 02339210: WEHADKEE CREEK NEAR PITTMAN AL",
  "subjectOf": "https://waterdata.usgs.gov/monitoring-location/02339210",
  "provider": "https://waterdata.usgs.gov",
  "provider_id": "02339210",
  "nhdpv2_REACHCODE": "03130002000353",
  "nhdpv2_REACH_measure": 9.594026996679105,
  "nhdpv2_COMID": 3291414,
  "id": "https://geoconnex.us/ref/gages/1029567"
}
```
```
uri_field=None, geojsonld=True
{
  "@context": [
    {
      "schema": "https://schema.org/name",
      "id": "@id",
      "type": "@type",
      "name": "schema:name",
      "description": "schema:description",
      "subjectOf": "schema:subjectOf"
    }
  ],
  "type": "Feature",
  "pygeoapi_id": 1029567,
  "fid": 1,
  "uri": "https://geoconnex.us/ref/gages/1029567",
  "name": "WEHADKEE CREEK NEAR PITTMAN AL",
  "description": "USGS NWIS Stream/River/Lake Site 02339210: WEHADKEE CREEK NEAR PITTMAN AL",
  "subjectOf": "https://waterdata.usgs.gov/monitoring-location/02339210",
  "provider": "https://waterdata.usgs.gov",
  "provider_id": "02339210",
  "nhdpv2_REACHCODE": "03130002000353",
  "nhdpv2_REACH_measure": 9.594026996679105,
  "nhdpv2_COMID": 3291414,
  "id": "http://localhost:5000/collections/gages/items/1029567"
}
```
```
uri_field=uri, geojsonld=False
{
  "@context": [
    "https://geojson.org/geojson-ld/geojson-context.jsonld",
    {
      "schema": "https://schema.org/name",
      "id": "@id",
      "type": "@type",
      "name": "schema:name",
      "description": "schema:description",
      "subjectOf": "schema:subjectOf"
    }
  ],
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      -85.3199473,
      33.22511878
    ]
  },
  "properties": {
    "fid": 1,
    "uri": "https://geoconnex.us/ref/gages/1029567",
    "name": "WEHADKEE CREEK NEAR PITTMAN AL",
    "description": "USGS NWIS Stream/River/Lake Site 02339210: WEHADKEE CREEK NEAR PITTMAN AL",
    "subjectOf": "https://waterdata.usgs.gov/monitoring-location/02339210",
    "provider": "https://waterdata.usgs.gov",
    "provider_id": "02339210",
    "nhdpv2_REACHCODE": "03130002000353",
    "nhdpv2_REACH_measure": 9.594026996679105,
    "nhdpv2_COMID": 3291414
  },
  "id": "https://geoconnex.us/ref/gages/1029567"
}
```
The links are removed for readability but are included in each JSON-LD response (this is easy to toggle).

**Comment by ksonda** [comment]
right so, like this I think. (context also includes whatever was declared in config.yml)
![image](https://user-images.githubusercontent.com/44071350/113935779-f1243c00-97c4-11eb-9d78-6d02734b8a62.png)

**Comment by webb-ben** [comment]
Use this command to explore my working solution!
`docker run -p 5000:80 -d --rm webbben/pygeoapi`
The URIs only work for the /items/ page to allow easier navigation to /items/[item] from the set.

**Comment by ksonda** [comment]
This gets us the functional json-ld we want for all four scenarios. Not sure the way schema:geo works here is pretty with the geojson coordinates staying there in this array that is hanging out alongside the "lat" and "lon" properties. It's linted the way it needs to though.

@dblodgett-usgs , due to the way pygeoapi is built, it looks like its necessary for in the json-ld for these ancilliary properties "id_" and "pygeoapi_id" to be there to correctly route the desired uri to the html templates and the canonical url, due to over-reliance throughout the rest of pygeoapi on the property "id". I don't know if geopython community will think this is a big deal. I don't think its a big deal because the geojson representation is unaffected.

**Comment by dblodgett-usgs** [comment]
We'll see what others think. I'd say let's go ahead and open a PR with this?

**Comment by ksonda** [comment]
mkay. Do you think a better reviewer to request is Tom K or Richard Law?

**Comment by dblodgett-usgs** [comment]
Probably Tom -- I'm not sure Richard has merge rights?

**Comment by ksonda** [comment]
draft PR https://github.com/ksonda/pygeoapi/pull/1#issue-616904932

**Comment by ksonda** [comment]
addressed by https://github.com/geopython/pygeoapi/pull/676
